/**
 * @file eps.c
 * @brief Implementation of the EPS task.
 * 
 */

#include "eps.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "health.h"
#include "flash.h"
#include "notifications.h"
#include "events.h"
// need to include ..hal.h
#include "main.h"
#include "stm32l4xx.h"
#include "task_management.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// I2C and sensor constants
#define DS2782_I2C_ADDR      0x34
#define DS2782_REG_START     0x06  // We start reading at the SOC register
#define I2C_TIMEOUT          50

// OBDH connbstants
#define OBDH_MAILBOX_ADDRESS    0x08030800 // memory address for OBDH payload (telemetry)
#define HEATER_CONFIG_ADDRESS   0x08031000 // permanent heater config

// Sensor multipliers (Not really needed we just want to send raw data)
// Current & Capacity assume a 10mOhm (0.01 Ohm) Sense Resistor
#define VOLTAGE_MULTIPLIER_V    0.00488f
#define CURRENT_MULTIPLIER_MA   0.15625f 
#define CAPACITY_MULTIPLIER_MAH 0.625f

extern I2C_HandleTypeDef hi2c1;

static bool paused;
/** @brief Notification bits deferred while the EPS task is paused. */
static uint32_t deferred_notifications;

static void setup_eps(void);
static void process_eps(void);

// heater
static bool g_mock_mode_enabled;
static bool auto_heat_enabled = false;
static uint8_t thresholds[3] = {4, 3.3, 3}; // needs to be changed (what to expect from OBDH)
// Nom, Cont, Safe

// Function prototypes
static uint32_t wait_for_notification(void);
static void EPS_Pack_Telemetry(const Battery_Telemetry_t *batt, const EPS_Status_t *pmic, OBDH_Payload_t *payload_out);
static HAL_StatusTypeDef send_telemetry_to_obdh(OBDH_Payload_t *payload);

void eps_task(void *pv_parameters)
{
    DS2782_Set_Mock_Mode(true);
    (void)pv_parameters;
    setup_eps();

    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
    }

}

/**
 * @brief Initialize EPS task state.
 */
static void setup_eps(void)
{
    deferred_notifications = 0;
    // Apply the default configuration

    // Recovery
    uint8_t saved_heater_conf = 0;

    if (OBDH_Read_Request(HEATER_CONFIG_ADDRESS, &saved_heater_conf, 1) == HAL_OK)
        auto_heat_enabled = (saved_heater_conf == 1);
    else
        auto_heat_enabled = false; // defaults to false

    // GPIOB10 OFF, eps will set it again if necessary
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
}


/**
 * @brief Execute one EPS task processing cycle. 
 *
 * Handles the task pause/resume protocol and processes pending EPS 
 * task notifications.
 */
static void process_eps(void)
{
    uint32_t notifications = wait_for_notification(pdMS_TO_TICKS(1000));

    if (tm_check_pause(notifications, &deferred_notifications))
        return;

    notifications |= deferred_notifications;
    deferred_notifications = 0;

    if (notifications & N_EPS_NEW_THRESHOLDS) {
        uint8_t thresholds[3] = {0}; // TODO define default theshholds in case of read failure
        OBDH_Read_Request(EPS_THRESHOLDS_ADDR, thresholds, 3); 
        // Thresholds are now in the thresholds array, in the order: 
        // thresholds[0]: nominal
        // thresholds[1]: contingency
        // thresholds[2]: sunsafe
    }

    if (notifications & N_EPS_ENABLE_AUTO_HEAT) {
        // TODO: TBD — enable EPS heater
        // Save configuration in OBDH if needed?

        auto_heat_enabled = true;
        uint8_t new_conf = 1;
        OBDH_Write_Request(HEATER_CONFIG_ADDRESS, &new_conf, 1);
    }

    if (notifications & N_EPS_DISABLE_AUTO_HEAT) {
        // TODO: TBD — disable EPS heater

        auto_heat_enabled = false;
        uint8_t new_conf = 0;
        OBDH_Write_Request(HEATER_CONFIG_ADDRESS, &new_conf, 1);
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
    }

    // Process other notifications as needed

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is
    // connected to the IC2 line 1 (SCL1,SDA1).
    // 3. Send to OBDH task for it to store to flash

    static Battery_Telemetry_t battery_sensor;
    static EPS_Status_t eps_status;
    static OBDH_Payload_t payload;
    bool battery_ok = DS2782_Read_Hardware(&battery_sensor);
    bool pmic_ok = LTC4040_Read_Hardware(&eps_status);

    if (battery_ok) {
        
        float vbat = DS2782_Compute_Voltage(&battery_sensor);
        float temp = DS2782_Compute_Temperature(&battery_sensor);

        if (vbat < 3.3f) {
            EPS_Charger_Disable(); // Forcem CHGOFF a HIGH per seguretat
            // Set EventGroup bits -> Alerta Crítica a l'OBDH
        }

        // 7. Auto-heater rules amb control de pins net mitjançant l'auxiliar
        if (temp < 5.0f) {
            EPS_Heater_Enable(); // PB10 a HIGH automàticament
        } else if (temp > 15.0f) {
            EPS_Heater_Disable(); // PB10 a LOW
        }

    } else {
        // fail logic

    }

    if (pmic_ok) {
        // pmic logic
    } else {
        //fail logic

    }

    // read heater status
    eps_status.auto_heater_enabled = auto_heat_enabled;
    eps_status.heater_state = EPS_Heater_Read();

    // read status
    eps_status.battery_read_failure = !battery_ok;
    eps_status.pmic_read_failure = !pmic_ok;

    EPS_Pack_Telemetry(&battery_sensor, &eps_status, &payload);

    HAL_StatusTypeDef i2c_status = send_telemetry_to_obdh(&payload);

    // 4. Update EPS Event Group bits with the current battery conditions
}

static uint32_t wait_for_notification(void)
{
    uint32_t notificationValue = 0;
    xTaskNotifyWait(0, 0xFFFFFFFF, &notificationValue, 0);
    return notificationValue;
}

static HAL_StatusTypeDef send_telemetry_to_obdh(OBDH_Payload_t *payload)
{
    return OBDH_Write_Request(
        OBDH_MAILBOX_ADDRESS, 
        (uint8_t*)payload, 
        sizeof(OBDH_Payload_t)
    );
}

// Helper functions:

void DS2782_Set_Mock_Mode(bool enable) {
    g_mock_mode_enabled = enable;
}

void EPS_Heater_Enable(void) {
    // pin PB10 HIGH enable heater
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_SET);
}

void EPS_Heater_Disable(void) {
    // pin PB10 LOW disable heater
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
}

bool EPS_Heater_Read(void) {
    // Read pin PB10 HIGH heater is enabled
    return (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_10));
}

void EPS_Charger_Enable(void) {
    // pin CHGOFF (PA3), LOW charging enabled
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_3, GPIO_PIN_RESET);
}

void EPS_Charger_Disable(void) {
    // pin CHGOFF (PA3), HIGH charging disabled
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_3, GPIO_PIN_SET);
}


bool DS2782_Read_Hardware(Battery_Telemetry_t *telemetry_out) {
    if (telemetry_out == NULL) return false;

    // Mock data
    if (g_mock_mode_enabled) {
        // (Battery 3.82V, 24.5ºC, consuming 150mA)
        telemetry_out->raw_voltage         = (uint16_t)(3.82f / 0.00488f);
        telemetry_out->raw_current         = (int16_t)(-150.0f / 0.104f);
        telemetry_out->raw_avg_current     = (int16_t)(-145.0f / 0.104f);
        telemetry_out->raw_temperature     = (int16_t)(24.5f / 0.125f);
        telemetry_out->raw_accumulated_cap = 2400; 
        telemetry_out->raw_relative_cap    = 78;   // 78% de bateria
        telemetry_out->raw_standby_relative_cap = 40;
        return true;
    }
}

bool LTC4040_Read_Hardware(EPS_Status_t *pmic_out) {
    if (pmic_out == NULL) return false;

    if (g_mock_mode_enabled) {
        // Simulació PMIC: Estem a l'espai sota el sol (No eclipse, carregant, sense fallades)
        pmic_out->is_charging        = true;  // !CHRG a 0V
        pmic_out->has_fault          = false; // !FAULT en High impedance (3.3V)
        pmic_out->is_eclipse         = false; // !PFO en High impedance (3.3V)
        pmic_out->raw_clprog_adc     = 2048;  // Mig rang ADC
        // --- Add additional analog readings later ---
        //pmic_out->raw_vsys_adc       = 3100;  // Raïl de 5V nominal estable
        //pmic_out->raw_killswitch_adc = 2900;  // Voltatge analògic
        //pmic_out->raw_batt_ntc_adc   = 1950;  // Temperatura equilibrada
        return true;
    }

    // OPERACIÓ FÍSICA: Llegir l'estat elèctric actual dels pins actius en LOW (Open-Drain)
    pmic_out->is_charging = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_2) == GPIO_PIN_RESET); // !CHRG (PB2)
    pmic_out->has_fault   = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_4) == GPIO_PIN_RESET); // !FAULT (PC4)
    pmic_out->is_eclipse  = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_5) == GPIO_PIN_RESET); // !PFO (PB5)
    // pmic_out->was_reset   = __HAL_RCC_GET_FLAG(RCC_FLAG_PINRST)                      // !RST

    // ADC readings (CLPROG)

    // Can be added later
    //pmic_out->raw_killswitch_adc = (uint16_t)HAL_ADC_GetValue(&hadc1);
    return true;
}

// Compute functions and payload logic

uint16_t DS2782_Compute_Voltage(const Battery_Telemetry_t *telemetry) {
    // in Volts using 4.88 mV
    return telemetry->raw_voltage * VOLTAGE_MULTIPLIER_V;
}

int16_t DS2782_Compute_Current(const Battery_Telemetry_t *telemetry) {
    // positive means charging, negative uncharging
    // using 0.104 mA
    return telemetry->raw_current * CURRENT_MULTIPLIER_MA;
}

int16_t DS2782_Compute_Temperature(const Battery_Telemetry_t *telemetry) {
    // Celsius
    return telemetry->raw_temperature * 0.125f;
}

void EPS_Pack_Telemetry(const Battery_Telemetry_t *batt, const EPS_Status_t *pmic, OBDH_Payload_t *payload_out) {
    // Safety check: Ensure pointers are not null before accessing memory
    if (batt == NULL || pmic == NULL || payload_out == NULL) {
        return; 
    }

    // --- raw I2C Battery Data ---
    payload_out->vbat_raw            = batt->raw_voltage;
    payload_out->current_raw         = batt->raw_current;
    payload_out->avg_current_raw     = batt->raw_avg_current;
    payload_out->temp_raw            = batt->raw_temperature;
    payload_out->accum_cap_raw       = batt->raw_accumulated_cap;
    payload_out->rel_cap_raw         = batt->raw_relative_cap;
    payload_out->standby_rel_cap_raw = batt->raw_standby_relative_cap;

    // --- Analog PMIC Data ---
    payload_out->clprog_adc          = pmic->raw_clprog_adc;
    /* --- Extra possible Analog readings that could be done --- */
    //payload_out->vsys_adc        = pmic->raw_vsys_adc;
    //payload_out->killswitch_adc  = pmic->raw_killswitch_adc;
    //payload_out->batt_ntc_adc    = pmic->raw_batt_ntc_adc;

    // --- Boolean Logic ---
    // (0000 0000)
    payload_out->system_status = 0x00; 

    // Pack the hardware booleans using bitwise OR
    if (pmic->is_charging) {
        payload_out->system_status |= (1 << 0); // Set Bit 0
    }
    if (pmic->has_fault) {
        payload_out->system_status |= (1 << 1); // Set Bit 1
    }
    if (pmic->is_eclipse) {
        payload_out->system_status |= (1 << 2); // Set Bit 2
    }
    if (pmic->charging_disabled) {
        payload_out->system_status |= (1 << 3); //Set bit 3
    }
    if (pmic->auto_heater_enabled) {
        payload_out->system_status |= (1 << 4); //Set bit 4
    }
    if (pmic->heater_state) {
        payload_out->system_status |= (1 << 5); //Set bit 5
    }
    if (pmic->battery_read_failure) {
        payload_out->system_status |= (1 << 6); //Set bit 6
    }
    if (pmic->pmic_read_failure) {
        payload_out->system_status |= (1 << 7); //Set bit 7
    }
}