/**
 * @file eps.c
 * @author your name (you@domain.com)
 * @brief The main functionality of the EPS task is providing the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * @version 0.1
 * @date 2026-01-20
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#include "eps.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "health.h"
#include "flash.h"
#include "notifications.h"
#include "events.h"
// need to include ..hal.h
#include "main.h"
#include "stm32l4xx.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// I2C and sensor constants
#define DS2782_I2C_ADDR      0x34
#define DS2782_REG_START     0x06  // We start reading at the SOC register
#define I2C_TIMEOUT          50

// OBDH connbstants
#define OBDH_MAILBOX_ADDRESS    0x08030800 // memory address for OBDH payload (telemetry)
#define HEATER_CONFIG_ADDRESS   0x08031000 // permanent heater config

// Sensor multipliers (Not really needed we just want to send raw data)
// Current & Capacity assume a 10mOhm (0.01 Ohm) Sense Resistor
#define VOLTAGE_MULTIPLIER_V    0.00488f
#define CURRENT_MULTIPLIER_MA   0.15625f 
#define CAPACITY_MULTIPLIER_MAH 0.625f

extern I2C_HandleTypeDef hi2c1;

static bool paused;
static uint32_t deferred_notifications;

// heater
static bool auto_heat_enabled = false;
static float thresholds[3] = {4.0f, 3.3f, 3.9f}; // needs to be changed (float?? what to expect from OBDH)
// Nom, Cont, Safe

// Function prototypes
static void setup_eps(void);
static void process_eps(void);
static uint32_t wait_for_notification(void);
static bool poll_battery_sensor(uint8_t *payload);
static HAL_StatusTypeDef send_telemetry_to_obdh(uint8_t *payload);

void eps_task(void *pv_parameters)
{

    setup_eps();

    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

}

static void setup_eps(void)
{
    paused = false;
    deferred_notifications = 0;
    // Apply the default configuration

    // Recovery
    uint8_t saved_heater_conf = 0;

    if (OBDH_Read_Request(HEATER_CONFIG_ADDRESS, &saved_heater_conf, 1) == HAL_OK)
        auto_heat_enabled = (saved_heater_conf == 1);
    else
        auto_heat_enabled = false; // defaults to false

    // GPIOB10 OFF, eps will set it again if necessary
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
}

static void process_eps(void)
{
    uint32_t notifications = wait_for_notification();

    if (paused) {
        deferred_notifications |= notifications & ~(N_TASK_PAUSE | N_TASK_RESUME);
        if (notifications & N_TASK_RESUME) {
            paused = false;
            notifications = deferred_notifications;
            deferred_notifications = 0;
            xEventGroupSetBits(task_events_handle, EV_TASK_ACK_EPS);
        }
        else return;
    }

    if (notifications & N_TASK_PAUSE) {
        deferred_notifications |= notifications & ~(N_TASK_PAUSE | N_TASK_RESUME);
        paused = true;
        xEventGroupSetBits(task_events_handle, EV_TASK_ACK_EPS);
        return;
    }

    if (notifications & N_EPS_NEW_THRESHOLDS) {
        uint8_t thresholds[3] = {0}; // TODO define default theshholds in case of read failure
        OBDH_Read_Request(EPS_THRESHOLDS_ADDR, thresholds, 3); 
        // Thresholds are now in the thresholds array, in the order: 
        // thresholds[0]: nominal
        // thresholds[1]: contingency
        // thresholds[2]: sunsafe
    }

    if (notifications & N_EPS_ENABLE_AUTO_HEAT) {
        // TODO: TBD — enable EPS heater
        // Save configuration in OBDH if needed?

        auto_heat_enabled = true;
        uint8_t new_conf = 1;
        OBDH_Write_Request(HEATER_CONFIG_ADDRESS, &new_conf, 1);
    }

    if (notifications & N_EPS_DISABLE_AUTO_HEAT) {
        // TODO: TBD — disable EPS heater

        auto_heat_enabled = false;
        uint8_t new_conf = 0;
        OBDH_Write_Request(HEATER_CONFIG_ADDRESS, &new_conf, 1);
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
    }

    // Process other notifications as needed

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is
    // connected to the IC2 line 1 (SCL1,SDA1).
    // 3. Send to OBDH task for it to store to flash
    uint8_t sensor_data[9] = {0};

    if (poll_battery_sensor(sensor_data) == true) 
    {   
        // heater part
        // math could be skipped, read this from OBDH? just wait for command? how should thresholds be (float)??
        uint16_t raw_voltage = (sensor_data[3] << 8) | sensor_data[4];
        float actual_voltage = (float)raw_voltage * VOLTAGE_MULTIPLIER_V;

        uint16_t raw_temp = (sensor_data[1] << 8) | sensor_data[2];
        float actual_temp = (float)raw_temp / 256.0f;


        //
        // Contingency Event Trigger
        if (actual_voltage < thresholds[1]) {
            //xEventGroupSetBits(task_events_handle, EV_BATT_CONTINGENCY);
        }

        // THERMOSTAT LOGIC
        if (actual_voltage <= thresholds[1]) {
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); 
        }
        else if (auto_heat_enabled == true) {
            // hysteresis
            if (actual_temp <= 2.0f) {
                HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_SET); 
            }
            else if (actual_temp >= 5.0f) {
                HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
            }
        }
        else {
            // DISABLED: Ensure hardware is off
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
        }

        // telemetry
        uint8_t telemetry_packet[10] = {0};
        
        memcpy(telemetry_packet, sensor_data, 9);
        
        uint8_t status_byte = 0;
        
        if (auto_heat_enabled) {
            status_byte |= (1 << 0); // Bit 0: Ground Config State
        }
        if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_10) == GPIO_PIN_SET) {
            status_byte |= (1 << 1); // Bit 1: Physical Heater State
        }
        if (actual_voltage <= thresholds[1]) {
            status_byte |= (1 << 2); // Bit 2: Contingency State
        }
        
        telemetry_packet[9] = status_byte; // Attach status byte to the end

        // Send unified packet to OBDH Mailbox
        send_telemetry_to_obdh(telemetry_packet);

        // check voltage contingency?
        // only sensor part
        //send_telemetry_to_obdh(sensor_data);
    }

    // 4. Update EPS Event Group bits with the current battery conditions
}

static uint32_t wait_for_notification(void)
{
    uint32_t notificationValue = 0;
    xTaskNotifyWait(0, 0xFFFFFFFF, &notificationValue, 0);
    return notificationValue;
}

static bool poll_battery_sensor(uint8_t *payload)
{
    uint8_t i2c_buffer[12] = {0};
    
    HAL_StatusTypeDef i2c_status = HAL_I2C_Mem_Read(
        &hi2c1, (DS2782_I2C_ADDR << 1), 0x06, 
        I2C_MEMADD_SIZE_8BIT, i2c_buffer, 12, 50
    );

    if (i2c_status == HAL_OK) 
    {
        payload[0] = i2c_buffer[0];  // SOC
        payload[1] = i2c_buffer[4];  // Temp MSB
        payload[2] = i2c_buffer[5];  // Temp LSB
        payload[3] = i2c_buffer[6];  // Volt MSB
        payload[4] = i2c_buffer[7];  // Volt LSB
        payload[5] = i2c_buffer[8];  // Curr MSB
        payload[6] = i2c_buffer[9];  // Curr LSB
        payload[7] = i2c_buffer[10]; // Cap MSB
        payload[8] = i2c_buffer[11]; // Cap LSB
        
        return true;
    }
    
    return false; // Failure -> TODO: How to handle failure
}

static HAL_StatusTypeDef send_telemetry_to_obdh(uint8_t *payload)
{
    return OBDH_Write_Request(
        OBDH_MAILBOX_ADDRESS, 
        payload, 
        10 // We know it is exactly 10 bytes (without heater info 9)
    );
}