/**
 * @file eps.c
 * @brief Implementation of the EPS task.
 * 
 */

#include "eps.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "health.h"
#include "flash.h"
#include "notifications.h"
#include "events.h" 
#include "main.h"
#include "stm32l4xx.h"
#include "task_management.h"

// The main functionality of the EPS task is providing the OBC with battery readings on 
// it's voltage, current generated, capacity, temperature and charging status. The task 
// will also indicate any error generated by the Power Management IC.

// I2C and sensor constants
#define DS2782_I2C_ADDR      0x34
#define DS2782_REG_START     0x06

// Battery state machine hysteresis (rising-direction only, in mV)
#define EPS_HYSTERESIS_MV    50u

extern I2C_HandleTypeDef hi2c1;

/** @brief Notification bits deferred while the EPS task is paused. */
static uint32_t deferred_notifications;

static TaskHandle_t eps_task_handle  = NULL;
static bool         auto_heat_enabled  = false;

// Unit convention: ALL voltages in mV, temperatures in °C, currents in mA.
// Stored in flash as 1 byte each in units of 100 mV (matches the 3-byte TC format).
static uint16_t thresholds_mv[3] = {3700, 3300, 3000}; // [0] nominal, [1] contingency, [2] sunsafe
static int8_t   heater_hysteresis_c[2] = {0, 5};       // ON below [0], OFF above [1]
static uint16_t sampling_period_100ms  = 10;           // 10 x 100 ms = 1 s default

volatile uint32_t eps_cycle_count = 0;

//eventGroup
EventGroupHandle_t batteryStatus = NULL;

// Function prototypes
static void setup_eps(void);
static void process_eps(void);
static HAL_StatusTypeDef send_telemetry_to_obdh(OBDH_Payload_t *payload);
static void load_thresholds_from_flash(void);
static void load_sampling_from_flash(void);
static void load_heater_bands_from_flash(void);

#ifdef UNIT_TEST
bool EPS_Mock_Mode_Active(void);
bool DS2782_Read_Mock(Battery_Telemetry_t *out);
bool LTC4040_Read_Mock(EPS_Status_t *out);
#endif

void eps_task(void *pv_parameters)
{
    eps_task_handle = xTaskGetCurrentTaskHandle();
    (void)pv_parameters;
    setup_eps();

    for (;;) {
        process_eps();
        health_kick(HEALTH_BIT_EPS);
    }

}

/**
 * @brief Initialize EPS task state.
 */
static void setup_eps(void)
{
    deferred_notifications = 0;

    batteryStatus = xEventGroupCreate();

    if (batteryStatus != NULL) {
        // Set the default startup state to NOMINAL on boot
        xEventGroupSetBits(batteryStatus, EV_BAT_NOMINAL);
    }

    // Apply the default configuration

    // Recovery
    uint8_t saved_heater_conf = 0;
    if (OBDH_Read_Request(HEATER_CONFIG_ADDR, &saved_heater_conf, 1) == HAL_OK)
        auto_heat_enabled = (saved_heater_conf == 1);
    else
        auto_heat_enabled = false;

    // GPIOB10 OFF, eps will set it again if necessary
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);

    // Restore charger state from flash; default to enabled on fresh flash (0xFF)
    uint8_t saved_charger_conf = 1;
    if (OBDH_Read_Request(CHARGER_CONFIG_ADDR, &saved_charger_conf, 1) == HAL_OK && saved_charger_conf != 0xFF) {
        if (saved_charger_conf == 1)
            EPS_Charger_Enable();
        else
            EPS_Charger_Disable();
    } else
        EPS_Charger_Enable();

    // recover thresholds:
    load_thresholds_from_flash();
    load_sampling_from_flash();
    load_heater_bands_from_flash();
}


/**
 * @brief Execute one EPS task processing cycle. 
 *
 * Handles the task pause/resume protocol and processes pending EPS 
 * task notifications.
 */
static void process_eps(void)
{
    uint32_t notifications = wait_for_notification(pdMS_TO_TICKS((uint32_t)sampling_period_100ms * 100u));

    if (tm_check_pause(notifications, &deferred_notifications))
        return;

    notifications |= deferred_notifications;
    deferred_notifications = 0;

    if (notifications & N_EPS_NEW_THRESHOLDS) {
        load_thresholds_from_flash();
        // Thresholds are now in the thresholds array, in the order: 
        // thresholds[0]: nominal
        // thresholds[1]: contingency
        // thresholds[2]: sunsafe 
    }

    if (notifications & N_EPS_NEW_SAMPLING)
        load_sampling_from_flash();

    if (notifications & N_EPS_NEW_HEATER_BANDS)
        load_heater_bands_from_flash();

    if (notifications & N_EPS_ENABLE_AUTO_HEAT) {
        // enable EPS heater and save to flash
        auto_heat_enabled = true;
        uint8_t new_conf = 1;
        OBDH_Write_Request(HEATER_CONFIG_ADDR, &new_conf, 1);
    }

    if (notifications & N_EPS_DISABLE_AUTO_HEAT) {
        auto_heat_enabled = false;
        uint8_t new_conf = 0;
        OBDH_Write_Request(HEATER_CONFIG_ADDR, &new_conf, 1);
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
    }

    if (notifications & N_EPS_ENABLE_CHARGER) {
        EPS_Charger_Enable();
        uint8_t conf = 1;
        OBDH_Write_Request(CHARGER_CONFIG_ADDR, &conf, 1);
    }

    if (notifications & N_EPS_DISABLE_CHARGER) {
        EPS_Charger_Disable();
        uint8_t conf = 0;
        OBDH_Write_Request(CHARGER_CONFIG_ADDR, &conf, 1);
    }

    if (notifications & N_EPS_FAULT_DETECTED) {
        // Charger already disabled by ISR. Persist the disabled state so it
        // survives a reboot. OBC re-enables via N_EPS_ENABLE_CHARGER.
        uint8_t conf = 0;
        OBDH_Write_Request(CHARGER_CONFIG_ADDR, &conf, 1);
    }

    // N_EPS_ECLIPSE_START / N_EPS_ECLIPSE_END: no software action needed.
    // The LTC4040 handles the power path automatically. is_eclipse is reflected
    // in telemetry via LTC4040_Read_Hardware() polling the !PFO pin each cycle.

    // 2. Poll battery sensor (DS2782E+) for voltage, current and capacity. This IC is
    // connected to the IC2 line 1 (SCL1,SDA1).
    // 3. Send to OBDH task for it to store to flash

    static Battery_Telemetry_t battery_sensor;
    static EPS_Status_t eps_status;
    static OBDH_Payload_t payload;
    bool battery_ok = DS2782_Read_Hardware(&battery_sensor);
    bool pmic_ok = LTC4040_Read_Hardware(&eps_status);

    if (battery_ok) {
        
        uint16_t vbat_mv = DS2782_Compute_Voltage(&battery_sensor);
        int16_t temp_c = DS2782_Compute_Temperature(&battery_sensor);

        // manage batteryStatus EventGroup
        EPS_Update_System_State(vbat_mv);

        // auto heater
        EPS_Heater_Control(temp_c);

    } else {
        // fail logic

    }

    if (pmic_ok) {
        if (eps_status.has_fault && !eps_status.charging_disabled) {
            EPS_Charger_Disable();
            uint8_t conf = 0;
            OBDH_Write_Request(CHARGER_CONFIG_ADDR, &conf, 1);
        }
    } else {
        //fail logic

    }

    // read heater status
    eps_status.auto_heater_enabled = auto_heat_enabled;
    eps_status.heater_state = EPS_Heater_Read();

    // read status
    eps_status.battery_read_failure = !battery_ok;
    eps_status.pmic_read_failure = !pmic_ok;

    EPS_Pack_Telemetry(&battery_sensor, &eps_status, &payload);

    HAL_StatusTypeDef i2c_status = send_telemetry_to_obdh(&payload);
    printf("[EPS] cycle %lu | batt_ok=%d pmic_ok=%d obdh=%d\r\n",
           eps_cycle_count, (int)battery_ok, (int)pmic_ok, (int)i2c_status);

    eps_cycle_count++;
}

static HAL_StatusTypeDef send_telemetry_to_obdh(OBDH_Payload_t *payload)
{
    return OBDH_Write_Request(
        OBDH_EPS_TELEMETRY_ADDR, 
        (uint8_t*)payload, 
        sizeof(OBDH_Payload_t)
    );
}

// Helper functions:

void EPS_Heater_Enable(void) {
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_SET);
}

void EPS_Heater_Disable(void) {
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
}

bool EPS_Heater_Read(void) {
    return (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_10));
}

void EPS_Charger_Enable(void) {
    // pin CHGOFF (PA3), LOW charging enabled
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_3, GPIO_PIN_RESET);
}

void EPS_Charger_Disable(void) {
    // pin CHGOFF (PA3), HIGH charging disabled
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_3, GPIO_PIN_SET);
}


bool DS2782_Read_Hardware(Battery_Telemetry_t *telemetry_out) {
    if (telemetry_out == NULL) return false;
#ifdef UNIT_TEST
    if (EPS_Mock_Mode_Active()) return DS2782_Read_Mock(telemetry_out);
#endif
    // TODO: real DS2782 burst read over I2C1 (HAL_I2C_Mem_Read, DS2782_I2C_ADDR
    return false;
}

bool LTC4040_Read_Hardware(EPS_Status_t *pmic_out) {
    if (pmic_out == NULL) return false;
#ifdef UNIT_TEST
    if (EPS_Mock_Mode_Active()) return LTC4040_Read_Mock(pmic_out);
#endif
    pmic_out->is_charging      = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_2) == GPIO_PIN_RESET); // !CHRG (PB2)
    pmic_out->has_fault        = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_4) == GPIO_PIN_RESET); // !FAULT (PC4)
    pmic_out->is_eclipse       = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_5) == GPIO_PIN_RESET); // !PFO (PB5)
    pmic_out->charging_disabled = (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_3) == GPIO_PIN_SET);  // CHROFF (PA3)
    // TODO: pmic_out->raw_clprog_adc = ADC read on PA4 (hadc1 channel 9)
    return true;
}

// Compute functions and payload logic

uint16_t DS2782_Compute_Voltage(const Battery_Telemetry_t *telemetry) {
    // millivolts: raw * 4.88 mV/LSB (max raw 1023 -> 4992 mV, fits uint16_t)
    return (uint16_t)(((uint32_t)telemetry->raw_voltage * 488u) / 100u);
}

/* DS2782_Compute_Current — enable for use of raw_current to Battery_Telemetry_t
int16_t DS2782_Compute_Current(const Battery_Telemetry_t *telemetry) {
    return (int16_t)(((int32_t)telemetry->raw_current * 5) / 32);
}
*/

int16_t DS2782_Compute_Temperature(const Battery_Telemetry_t *telemetry) {
    // degrees Celsius: raw * 0.125 C/LSB (truncates toward zero)
    return (int16_t)(telemetry->raw_temperature / 8);
}

void EPS_Pack_Telemetry(const Battery_Telemetry_t *batt, const EPS_Status_t *pmic, OBDH_Payload_t *payload_out) {
    // Safety check: Ensure pointers are not null before accessing memory
    if (batt == NULL || pmic == NULL || payload_out == NULL) {
        return; 
    }

    // --- raw I2C Battery Data ---
    payload_out->vbat_raw    = batt->raw_voltage;
    payload_out->temp_raw    = batt->raw_temperature;
    payload_out->rel_cap_raw = batt->raw_relative_cap;
    // payload_out->current_raw   = batt->raw_current;         // enable with raw_current
    // payload_out->accum_cap_raw = batt->raw_accumulated_cap; // enable if energy accounting needed

    // --- Analog PMIC Data ---
    payload_out->clprog_adc  = pmic->raw_clprog_adc;

    // --- Boolean Logic ---
    // (0000 0000)
    payload_out->system_status = 0x00; 
    if (pmic->is_charging) {
        payload_out->system_status |= (1 << 0);
    }
    if (pmic->has_fault) {
        payload_out->system_status |= (1 << 1);
    }
    if (pmic->is_eclipse) {
        payload_out->system_status |= (1 << 2);
    }
    if (pmic->charging_disabled) {
        payload_out->system_status |= (1 << 3);
    }
    if (pmic->auto_heater_enabled) {
        payload_out->system_status |= (1 << 4);
    }
    if (pmic->heater_state) {
        payload_out->system_status |= (1 << 5);
    }
    if (pmic->battery_read_failure) {
        payload_out->system_status |= (1 << 6);
    }
    if (pmic->pmic_read_failure) {
        payload_out->system_status |= (1 << 7);
    }
}

/**
 * @brief Update batteryStatus event group based on measured voltage.
 *
 * Implements an asymmetric hysteresis state machine:
 *   - Falling transitions (toward more severe state) are immediate and may
 *     skip intermediate states in a single call. Battery protection takes
 *     precedence over response smoothness.
 *   - Rising transitions (toward less severe state) advance one state per
 *     call and require voltage to exceed the threshold by EPS_HYSTERESIS_MV.
 *     This suppresses load-sag flap and ensures recovery is real.
 *
 * @param vbat_mv Measured battery voltage in millivolts.
 */
void EPS_Update_System_State(uint16_t vbat_mv)
{
    if (batteryStatus == NULL)
        return;

    uint32_t current_state = xEventGroupGetBits(batteryStatus) & ALL_BATTERY_STATES;
    uint32_t new_state     = current_state;

    switch (current_state) {
        case EV_BAT_NOMINAL:
            if      (vbat_mv < thresholds_mv[2]) new_state = EV_BAT_SURVIVAL;
            else if (vbat_mv < thresholds_mv[1]) new_state = EV_BAT_SUNSAFE;
            else if (vbat_mv < thresholds_mv[0]) new_state = EV_BAT_CONTINGENCY;
            break;

        case EV_BAT_CONTINGENCY:
            if      (vbat_mv < thresholds_mv[2]) new_state = EV_BAT_SURVIVAL;
            else if (vbat_mv < thresholds_mv[1]) new_state = EV_BAT_SUNSAFE;
            else if (vbat_mv >= thresholds_mv[0] + EPS_HYSTERESIS_MV)
                                                 new_state = EV_BAT_NOMINAL;
            break;

        case EV_BAT_SUNSAFE:
            if      (vbat_mv < thresholds_mv[2]) new_state = EV_BAT_SURVIVAL;
            else if (vbat_mv >= thresholds_mv[1] + EPS_HYSTERESIS_MV)
                                                 new_state = EV_BAT_CONTINGENCY;
            break;

        case EV_BAT_SURVIVAL:
            if (vbat_mv >= thresholds_mv[2] + EPS_HYSTERESIS_MV)
                                                 new_state = EV_BAT_SUNSAFE;
            break;

        default:
            break;
    }

    if (new_state != current_state) {
        xEventGroupClearBits(batteryStatus, ALL_BATTERY_STATES);
        xEventGroupSetBits(batteryStatus, new_state);
    }
}

/** Auto-heater hysteresis. Only acts when auto-heat is enabled by telecommand. */
void EPS_Heater_Control(int16_t temp_c)
{
    if (!auto_heat_enabled)
        return;
    if (temp_c < heater_hysteresis_c[0])
        EPS_Heater_Enable();
    else if (temp_c > heater_hysteresis_c[1])
        EPS_Heater_Disable();
}

/** Load thresholds from flash; keep current values if the data is implausible. */
static void load_thresholds_from_flash(void)
{
    uint8_t raw[3];
    if (OBDH_Read_Request(EPS_THRESHOLDS_ADDR, raw, 3) != HAL_OK)
        return;
    for (int i = 0; i < 3; i++)
        if (raw[i] < 25 || raw[i] > 45)      // plausible battery range 2.5–4.5 V
            return;
    if (!(raw[0] > raw[1] && raw[1] > raw[2])) // must be strictly descending
        return;
    for (int i = 0; i < 3; i++)
        thresholds_mv[i] = (uint16_t)raw[i] * 100u;
}

/** Load sampling period from flash; reject erased/zero values, clamp the minimum. */
static void load_sampling_from_flash(void)
{
    uint16_t raw;
    if (OBDH_Read_Request(EPS_SAMPLING_ADDR, (uint8_t *)&raw, 2) != HAL_OK)
        return;
    if (raw == 0x0000u || raw == 0xFFFFu)    // unprogrammed / erased flash
        return;
    if (raw < 5u)                            // DS2782 updates every ~440 ms; floor 500 ms
        raw = 5u;
    sampling_period_100ms = raw;
}

/** Load heater hysteresis bands from flash. Requires upper > lower with a
 *  minimum 2 °C deadband to prevent relay chatter near the threshold. */
static void load_heater_bands_from_flash(void)
{
    int8_t raw[2];
    if (OBDH_Read_Request(HEATER_BANDS_ADDR, (uint8_t *)raw, 2) != HAL_OK)
        return;
    if ((uint8_t)raw[0] == 0xFFu && (uint8_t)raw[1] == 0xFFu)   // erased flash
        return;
    if ((int)raw[1] - (int)raw[0] < 2)        // require minimum 2 °C deadband
        return;
    heater_hysteresis_c[0] = raw[0];
    heater_hysteresis_c[1] = raw[1];
}

/**
 * @brief Called from EXTI4_IRQHandler in stm32l4xx_it.c (PC4 !FAULT, falling edge).
 *
 * Disables the charger immediately — GPIO write is ISR-safe.
 * Wakes eps_task via notification so it can persist the disabled state to flash.
 */
void EPS_Fault_IRQHandler(void)
{
    EPS_Charger_Disable();

    if (eps_task_handle != NULL) {
        BaseType_t woken = pdFALSE;
        xTaskNotifyFromISR(eps_task_handle, N_EPS_FAULT_DETECTED, eSetBits, &woken);
        portYIELD_FROM_ISR(woken);
    }
}

/**
 * @brief Called from EXTI9_5_IRQHandler in stm32l4xx_it.c (PB5 !PFO, both edges).
 *
 * Reads the current pin state to distinguish eclipse start (falling) from eclipse
 * end (rising) and wakes eps_task. No hardware action — LTC4040 handles the power
 * path automatically.
 */
void EPS_PFO_IRQHandler(void)
{
    if (eps_task_handle != NULL) {
        uint32_t notif = (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_5) == GPIO_PIN_RESET)
                         ? N_EPS_ECLIPSE_START
                         : N_EPS_ECLIPSE_END;
        BaseType_t woken = pdFALSE;
        xTaskNotifyFromISR(eps_task_handle, notif, eSetBits, &woken);
        portYIELD_FROM_ISR(woken);
    }
}

#ifdef UNIT_TEST
void EPS_Test_Set_Thresholds_mV(const uint16_t mv[3])
{
    for (int i = 0; i < 3; i++) thresholds_mv[i] = mv[i];
}
void EPS_Test_Set_Auto_Heat(bool enable) { auto_heat_enabled = enable; }
#endif
