/**
 * @file eps.h
 * @brief Provides the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * 
 */

#ifndef INC_EPS_H_
#define INC_EPS_H_

/**
 * @brief EPS FreeRTOS task entry point.
 * @param pv_parameters Task parameter provided by xTaskCreate(); currently unused.
 */
void eps_task(void *pv_parameters);

#endif /* INC_EPS_H_ */

