/**
 * @file eps.h
 * @brief Provides the OBC with battery readings on 
    it's voltage, current generated, capacity, temperature and charging status. The task 
    will also indicate any error generated by the Power Management IC.
 * 
 */

#ifndef INC_EPS_H_
#define INC_EPS_H_
#ifndef DS2782_DRIVER_H
#define DS2782_DRIVER_H

#include <stdint.h>
#include <stdbool.h>


/**
 * @brief EPS FreeRTOS task entry point.
 * @param pv_parameters Task parameter provided by xTaskCreate(); currently unused.
 */
void eps_task(void *pv_parameters);

// DS2782 raw data
typedef struct {
    uint16_t raw_voltage;             // 4.88 mV/LSB
    // int16_t  raw_current;          // 0.104 mA/LSB — avg vs. instant decided by hardware team
    int16_t  raw_temperature;         // 0.125 ºC/LSB
    uint8_t  raw_relative_cap;        // 1% State of Charge (RARC)
    // uint16_t raw_accumulated_cap;  // 0.4167 mAh/LSB — enable if energy accounting needed
} Battery_Telemetry_t;

// LTC4040 (PMIC) data
typedef struct {
    bool    is_charging;           // pin !CHRG (true = charging)
    bool    has_fault;             // pin !FAULT (true = emergency fault)
    bool    is_eclipse;            // pin !PFO (true = eclipse active)
    bool    charging_disabled;     // pin CHROFF status (true = charging disabled)

    uint16_t raw_clprog_adc;       // ADC value of generated solar current

    // auto heater status
    bool auto_heater_enabled;
    bool heater_state;

    // read status
    bool battery_read_failure;
    bool pmic_read_failure;
} EPS_Status_t;


/* --- Hardware set functions --- */

// Use mocked data and not real hardware
void DS2782_Set_Mock_Mode(bool enable);

// Heater (Pin PB10)
void EPS_Heater_Enable(void);
void EPS_Heater_Disable(void);
bool EPS_Heater_Read(void);

//  LTC4040 Pin PA3 - CHGOFF
void EPS_Charger_Enable(void);
void EPS_Charger_Disable(void);


/* --- Hardware reading functions --- */

// Realitza el burst read complet del sensor I2C (Suporta mode simulació)
bool DS2782_Read_Hardware(Battery_Telemetry_t *telemetry_out);

// Realitza el sondeig (polling) dels canals analògics i digitals del PMIC
bool LTC4040_Read_Hardware(EPS_Status_t *pmic_out);


/* --- Compute values from read data functions --- */

uint16_t DS2782_Compute_Voltage(const Battery_Telemetry_t *telemetry);
// int16_t DS2782_Compute_Current(const Battery_Telemetry_t *telemetry);  // enable with raw_current
int16_t DS2782_Compute_Temperature(const Battery_Telemetry_t *telemetry);

// Force the compiler to pack this struct with ZERO empty padding bytes
#pragma pack(push, 1)

typedef struct {
    // 1. Digital Battery Sensor Data (DS2782) - 5 Bytes
    uint16_t vbat_raw;
    int16_t  temp_raw;
    uint8_t  rel_cap_raw;
    // int16_t  current_raw;     // enable when hardware team selects avg vs. instant register
    // uint16_t accum_cap_raw;   // enable if energy accounting needed

    // 2. Analog Power Manager Data (LTC4040 ADCs) - 2 Bytes
    uint16_t clprog_adc;

    // 3. Compressed Status Word - 1 Byte
    uint8_t  system_status;

} OBDH_Payload_t;

// Restore normal compiler padding for the rest of the code
#pragma pack(pop)

/* --- Pure logic, exposed for unit testing and reuse --- */
void EPS_Pack_Telemetry(const Battery_Telemetry_t *batt, const EPS_Status_t *pmic,
                        OBDH_Payload_t *payload_out);
void EPS_Update_System_State(uint16_t vbat_mv);
void EPS_Heater_Control(int16_t temp_c);

/* --- Hardware interrupt dispatch (called from stm32l4xx_it.c) --- */
void EPS_Fault_IRQHandler(void);   /**< PC4 !FAULT falling edge — disables charger immediately */
void EPS_PFO_IRQHandler(void);     /**< PB5 !PFO both edges — eclipse start/end detection */

/* --- Mock injection (debug facility; used by the on-target tests) --- */
void DS2782_Set_Mock_Values(const Battery_Telemetry_t *v);
void DS2782_Set_Mock_Fail(bool fail);
void LTC4040_Set_Mock_Values(const EPS_Status_t *v);
void LTC4040_Set_Mock_Fail(bool fail);

#ifdef UNIT_TEST
/* Test-only seams, compiled exclusively in the EPS_TESTS build */
void EPS_Test_Set_Thresholds_mV(const uint16_t mv[3]);
void EPS_Test_Set_Auto_Heat(bool enable);
extern volatile uint32_t eps_cycle_count;   /* ++ at end of each process_eps */
#endif


#endif /* DS2782_DRIVER_H */
#endif /* INC_EPS_H_ */

